language: node_js
node_js:
  - 6
after_success: npm run coverage
services:
  - postgresql
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
script:
  - npm test
  - npm run compile-dist
  - npm run build
after_script:
  - npm run coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: aMfP2hy00tke2GTZ56Xgg4VKu8Lubr7apneWQffK6Qvy1d4P3nNEnDUn8RX3xSR8jLjVBqZ3ujvbCSHlx6yg2RP5uZiQP8ECEMZkJZUZCss+bURxaxQPx+IYMr4woRmAVWGI6fSQY+wgbdgcLuMtXa2R9Wrn9S66qnyNRhgv7q9367P65Ek1KeRU8nU5tn1E6WRXIcK2K0Ak1dx6B/ZBZhmvjsFkcNjvgCSLW2vj/fApN5ilTrmecrHo9WAK99oWllTs9jjZ7fk6RkH8eXnYa5+QzltwiYFEFtwYXHXeBsy1u7hoBKod0Bj//YRkziK96puVID2cGdcw8x4+48slV+T/o+gcCzie414lkjAQuwNa31Wkovhk5vAx5vnuUj0Vrc8iE6bmSVsReKC6UgI68ULHDJZR3Rp7o70LJC2SYd7M0R+CHdnwK/JSyAbr6jFPk00JomY4wFIIzZLu50bOO83xmRjOgaInCesGuI4NeUaRnvUIY4g6JqEfP8mVpIMY7pNBTzwHh2begMV6jNeYe/EHfDTyii3QskBmhksxNLdZZ1ycpayrva6wKoH0TZ+bFiirSibpfE4xFRVmW/xlNxHofDY68LUsJ2eTc0l+HJtpZrhPxHecPu89Z//OizuYYOq7nNFmCK8tvTtWm7U7p5PW67Bx1Ks3ZxvWnoSY33w=
  app: docgenie
  on:
    repo: MemunaHaruna/DocGenie
    branch: staging
